DELETE  http://localhost:8081/events/1/register 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTczODIwOTg1OSwidXNlcklkIjoyfQ.l1PSQbQIJhmVErJKwnwqj5Yathsh7HPyc84Fmr9bgzM
